# Generated by Django 4.1.6 on 2023-08-28 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("different", "Different"),
                            ("not_specified", "Not Specified"),
                        ],
                        default="not_specified",
                        max_length=20,
                    ),
                ),
                (
                    "place_of_residence_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, default="", max_digits=9
                    ),
                ),
                (
                    "place_of_residence_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, default="", max_digits=9
                    ),
                ),
                (
                    "year_of_birth",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2022),
                            django.core.validators.MinValueValidator(1920),
                        ]
                    ),
                ),
                (
                    "user_avatar",
                    models.URLField(
                        default=pathlib.PurePosixPath("without_avatar.webp")
                    ),
                ),
                ("user_description", models.TextField()),
                (
                    "interest_hashtags",
                    models.ManyToManyField(
                        blank=True, to="user_profile.interesthashtag"
                    ),
                ),
                (
                    "login",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like_added", models.DateTimeField()),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("from_person", "to_person")},
            },
        ),
    ]
