# Generated by Django 4.1.6 on 2023-08-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="place_of_residence_latitude",
            new_name="city_of_residence_latitude",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="place_of_residence_longitude",
            new_name="city_of_residence_longitude",
        ),
    ]
