# Generated by Django 4.1.6 on 2023-09-04 08:03

from django.db import migrations, models

import user_profile.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0002_rename_place_of_residence_latitude_userinfo_city_of_residence_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="interest_hashtags",
        ),
        migrations.AlterField(
            model_name="interesthashtag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="likes",
            name="like_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="user_avatar",
            field=models.ImageField(
                blank=True, upload_to=user_profile.models.user_directory_path
            ),
        ),
    ]
